---
# handlers file for R80_Policy
- name: Publish Handeler
  check_point.mgmt.cp_mgmt_publish:
  notify: Install Access Policy

- name: Install Access Policy 
  check_point.mgmt.cp_mgmt_install_policy:
    access: true
    threat_prevention: false
    policy_package: "{{ policy_name }}"
    targets: "{{ policy_targets }}"
  notify: Install Threat Policy
  when: No_Policy_Install is not defined

- name: Install Threat Policy
  check_point.mgmt.cp_mgmt_install_policy:
    access: false
    threat_prevention: true
    policy_package: "{{ policy_name }}"
    targets: "{{ policy_targets }}"
  when: No_Policy_Install is not defined
